import org.jetbrains.kotlin.gradle.dsl.JvmTarget

// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    ext {
        kotlin_version = '1.9.24'
    }
    repositories {
        mavenCentral()
        google()
    }
    dependencies {
        // For KGP
        classpath(libs.kotlin.gradle.plugin)

        // For KSP
        //noinspection UseTomlInstead
        classpath("com.google.devtools.ksp:symbol-processing-gradle-plugin:KSP_VERSION")
    }
}
plugins {
    alias(libs.plugins.android.library) apply false
}

allprojects {
    configurations.configureEach {
        resolutionStrategy {
            eachDependency { details ->
                if (details.requested.group == 'org.jetbrains.kotlin' && details.requested.name.startsWith('kotlin-stdlib-jdk')) {
                    details.useTarget("org.jetbrains.kotlin:kotlin-stdlib:1.9.24")
                }
            }
        }
    }
}
